- name: complete the job
  hosts: all
  tasks:
    - name: complete
      uri:
        url: "{{ drmon_api }}/jobs/complete/{{ drmonJobID }}"
        method: PUT
        headers:
          Authorization: "{{ drmonToken }}"
        force_basic_auth: no
        validate_certs: False
        body_format: json
        body: '{ "result": "{{ jobResult }}" }'
      register: content
      until: content.status == 200
